name: Sync and Build Hexo

on:
  schedule:
    - cron: '0 0 15 * *'  # 每月15号 UTC 0点运行
  workflow_dispatch:

jobs:
  sync-and-build:
    runs-on: ubuntu-latest

    steps:
    # 步骤1：检出当前仓库（需要写权限）
    - name: Checkout with write access
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1  # 浅克隆优化速度

    # 步骤2：配置 Git 身份
    - name: Setup Git identity
      run: |
        git config --global user.name "Sync Bot"
        git config --global user.email "actions@users.noreply.github.com"

    # 步骤3：强制同步并保留关键文件
    - name: Force sync with file retention
      run: |
        # 确保获取当前仓库最新状态
        git fetch origin master --depth=1 --force

        # 添加上游仓库
        git remote add upstream https://github.com/hexojs/hexo.git 2> /dev/null || true
        
        # 获取上游最新代码
        git fetch upstream master --depth=1 --force
        
        # 重置到上游状态（此时会丢失本地文件）
        git reset --hard upstream/master
        
        # 恢复需要保留的 workflow 文件（从当前仓库的 origin/master）
        git checkout origin/master -- .github/workflows/mkz9s4vy-build-image.yml
        git checkout origin/master -- Dockerfile  # 保留你的 Dockerfile
        git checkout origin/master -- entrypoint.sh
        git checkout origin/master -- README.md
        
        # 提交合并和保留的文件
        git add -A
        git commit -m "Merge upstream changes & retain custom files"

        # 强制推送到当前仓库（进度显示，防止覆盖他人提交）
        git push --progress --force-with-lease origin HEAD

    # 后续 Docker 构建步骤保持不变
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set Version
      id: set-version
      run: |
        echo "version=$(date +'%y-%m-%d')" >> $GITHUB_ENV

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/mkz9s4vy/hexo_docker:${{ env.version }}
          ghcr.io/mkz9s4vy/hexo_docker:latest
